Add variables
George-lewis/rustcalc pull request #5
Opened 2021-04-28 02:25 UTC by kinseyda

I added functionality to allow for user defined variables, accessible by prefixing with a $
This includes
- Recalling the previous evaluated answer using `$ans`.
- Assigning any value (including the result of a expression) to a variable with an arbitrary name given by the user.
        -  e.g. `>$num = 5` and recalling with `2 + $num + 3`
- Reassigning the value of a variable using the same syntax.

2021-04-28 03:56 UTC, George-lewis requested changes
Needs some more work. Most of it is general fixes like making things more idiomatic, or some reorganization, but there are a few major issues like the structure of `main.rs`.

2021-04-28 03:56 UTC, George-lewis commented on src/lib/errors.rs
> +    Assignment,
The `/lib` directory should be treated as an entirely separate logical unit from the CLI code, the CLI just consumed the library. Thus, this error enum is only for library errors.

2021-04-28 03:56 UTC, George-lewis commented on src/lib/mod.rs
> +pub(crate) mod variables;
```suggestion
pub mod variables;
```

2021-04-28 03:56 UTC, George-lewis commented on src/lib/tokenize.rs
> +        let kind;
Not idiomatic. In Rust you can assign to expressions, like:

```rust
let kind = if condition {
  a
} else {
  b
}
```

2021-04-28 03:56 UTC, George-lewis commented on src/lib/tokenize.rs
> +        if c =='$' {
Refactor into `Variable::is` and then move it into `_type()`

2021-04-28 03:56 UTC, George-lewis commented on src/lib/tokenize.rs
> -        let kind = match _type(&slice) {
Why was this moved?

2021-04-28 03:56 UTC, George-lewis commented on src/lib/tokenize.rs
> +                idx += n+1; //+1 to account for '$'
Please insert a space between `//` and the start of a comment.

2021-04-28 03:56 UTC, George-lewis commented on src/lib/tokens.rs
> +            Self::Variable { inner } => "$".to_owned() + &inner.repr.to_string(),
```suggestion
            Self::Variable { inner } => format!("${}", inner.repr),
```

2021-04-28 03:56 UTC, George-lewis commented on src/lib/variables.rs
> +#![allow(clippy::non_ascii_literal)]
Might be unnecessary. Try removing and running `cargo clippy`.

2021-04-28 03:56 UTC, George-lewis commented on src/main.rs
> +    let mut vars: Vec<Variable> = Vec::new();
1. Use the `vec!` macro
2. Use `String::from` for constant `String` values

```suggestion
    let mut vars = vec![
      Variable {
        repr: String::from("ans"),
        value: 0.0
      }
    ]
```

2021-04-28 03:56 UTC, George-lewis commented on src/main.rs
> +            continue;
Probably better to do if/else. You could also factor out the `add_history_entry` line as a result.

2021-04-28 03:56 UTC, George-lewis commented on src/main.rs
> +                    ("$".to_owned() + &v.repr).green().bold(),
Use `format!`

2021-04-28 03:56 UTC, George-lewis commented on src/main.rs
> +            //Variable list command
```suggestion
            // Variable list command
```

2021-04-28 03:56 UTC, George-lewis commented on src/main.rs
> +            //Variable assignment/reassignment
```suggestion
            // Variable assignment/reassignment
```

2021-04-28 03:56 UTC, George-lewis commented on src/main.rs
> +            let sides: Vec<&str> = input.split('=').collect();
Trim before collecting.

2021-04-28 03:56 UTC, George-lewis commented on src/main.rs
> +                    handle_errors(e, input.clone(), sides[0].len() + 1);
Why `+1`?

2021-04-28 03:56 UTC, George-lewis commented on src/main.rs
> +        let mut test_vars: Vec<Variable> = Vec::new();
Use `vec!` like at the top of `main()`.

2021-04-28 03:56 UTC, George-lewis commented on src/lib/variables.rs
> +        let search_str = utils::slice(search, 1, -0); //to ignore $
We should probably be slicing in the outer layer (in the tokenizing code). `utils::slice` is specifically to handle unicode, however because we know the current character will be `$` in the relevant context you pay be able to get away with a cheaper slice: `&str[1..]`, which in theory should be as simple as passing a pointer...

2021-04-28 03:56 UTC, George-lewis commented on src/main.rs
> +fn handle_errors(e: Error, input: String, offset: usize) {
This feels kind of inverted, in `main()` you invoke this function directly in a lot of places. It would be better to encapsulate  most of the logic that's currently there into a new function, perhaps `fn handle_input(&str, ...?) -> Result<?>`. Feel free to define a new error enum specifically for the CLI half of the code. I can then imagine `main()` looking something like this:

```rust
// main()
match handle_input(&editor, &mut vars) {
  Ok(string) => println!( ... ),
  Err(e) => handle_error(e)
}
```

But I'm not completely sure. I might need to think about this more.

2021-04-28 03:56 UTC, George-lewis commented on src/main.rs
>      fn test() {
Create a new test function for the cli / var specific stuff.

2021-04-28 17:06 UTC, kinseyda commented on src/lib/tokenize.rs
> +        let kind;
Fixed as of #6680a94a7db7e5138fa0ee1ebec27250b4c9a426

2021-04-28 17:12 UTC, kinseyda commented on src/main.rs
> +            //Variable assignment/reassignment
Fixed as of 2b46055758992c2ff671cdfb1b9ebbbc810b0007

2021-04-28 17:12 UTC, kinseyda commented on src/main.rs
> +            //Variable list command
Fixed as of 2b46055758992c2ff671cdfb1b9ebbbc810b0007

2021-04-28 17:12 UTC, kinseyda commented on src/lib/tokenize.rs
> +                idx += n+1; //+1 to account for '$'
Fixed as of 2b46055758992c2ff671cdfb1b9ebbbc810b0007

2021-04-28 17:38 UTC, kinseyda commented on src/lib/tokenize.rs
> +        if c =='$' {
Fixed as mentioned, see 53aa5e7903f46d75699345d5f6c8336428b09bdd

2021-04-28 17:39 UTC, kinseyda commented on src/lib/tokenize.rs
> -        let kind = match _type(&slice) {
The kind variable assignment has been moved back to right before it is needed as it was originally, see 53aa5e7903f46d75699345d5f6c8336428b09bdd

2021-04-28 18:18 UTC, kinseyda commented on src/main.rs
> +                    ("$".to_owned() + &v.repr).green().bold(),
Fixed as of 76048df83f3dc74449819f2133a17b18e04f614b

2021-04-28 18:19 UTC, kinseyda commented on src/lib/tokens.rs
> +            Self::Variable { inner } => "$".to_owned() + &inner.repr.to_string(),
Fixed as of 76048df83f3dc74449819f2133a17b18e04f614b

2021-04-28 18:21 UTC, kinseyda commented on src/lib/variables.rs
> +#![allow(clippy::non_ascii_literal)]
Fixed with 695aa48043b171c3e83792d39d662ac2bab65576

2021-04-28 18:25 UTC, kinseyda commented on src/main.rs
> +    let mut vars: Vec<Variable> = Vec::new();
Good call, much neater. Changed with 127dbe606ed8df144f0be1a1471a82e7dbdc8190

2021-04-28 18:35 UTC, George-lewis requested changes

2021-04-28 18:35 UTC, George-lewis commented on src/main.rs
> +        .for_each(|(a, b)| assert_eq!(doeval(a, &Vec::new()).unwrap_err(), *b));
`&[]`

2021-04-28 22:29 UTC, kinseyda commented on src/main.rs
> +fn handle_errors(e: Error, input: String, offset: usize) {
This has been fixed with 7974f77fc31db1279175c5e2d3ed34ab9f8fff3a and 104fb771e8228d22e69f3b2709d0d0f4d1ae61ca.
Mostly it is as you specified above though I've added no new errors, instead just bubbling up the existing ones. The code in the main loop is now a lot more logically laid out and should be easier to follow.

2021-04-28 22:31 UTC, kinseyda commented on src/main.rs
> +            continue;
Resolved with 7974f77fc31db1279175c5e2d3ed34ab9f8fff3a, input handling now works via `if`/`else if`/`else `statements and not `continue`s

2021-04-28 22:42 UTC, George-lewis commented on src/main.rs
> +fn handle_errors(e: Error, input: String) {
```suggestion
fn handle_errors(error: Error, input: &str) {
```

This function should probably take a `&str` instead, and as a personal preference I'd like to see a longer-than-one variable name here.

2021-04-28 22:51 UTC, kinseyda commented on src/main.rs
> +            let sides: Vec<&str> = input.split('=').collect();
The left hand side of the assignment is the only part that really needs to be trimmed (since variables need to start with $, and any white space after the variable name but before the = sign shouldn't be included in names), but I've reduced the calls to trim() to just 1 with be546457fbc7d9c02585f7e4bc34e5a73b9275a9.

2021-04-28 23:08 UTC, kinseyda commented on src/main.rs
> +fn handle_errors(e: Error, input: String) {
Fixed with 16a1aaaa8cf7bb41804a6107c0c580ce5d3004b6

2021-04-28 23:19 UTC, kinseyda commented on src/main.rs
> +        .for_each(|(a, b)| assert_eq!(doeval(a, &Vec::new()).unwrap_err(), *b));
Resolved with 2fd49ed62a38ee138edbf263609df4c0e2aa2141

2021-04-28 23:19 UTC, kinseyda commented on src/main.rs
>      fn test() {
Resolved with 2fd49ed62a38ee138edbf263609df4c0e2aa2141

2021-04-28 23:20 UTC, kinseyda commented on src/main.rs
> +        let mut test_vars: Vec<Variable> = Vec::new();
Resolved with 2fd49ed62a38ee138edbf263609df4c0e2aa2141

2021-04-28 23:31 UTC, kinseyda commented on src/lib/variables.rs
> +        let search_str = utils::slice(search, 1, -0); //to ignore $
Resolved as stated with f895f1fc569766509614f612eb5b0d9e3ad7efd3

2021-04-29 01:31 UTC, George-lewis commented on src/main.rs
> +            let sides: Vec<&str> = input.split('=').collect();
And we don't have to trim the right side because the tokenizer can deal with whitespace on its own? Hmmm, alright.

2021-04-29 01:39 UTC, George-lewis requested changes
Please add some docs on new functions, eventually I (or someone else?) will add docs to the rest.

Documentation in Rust is done with Markdown. You can see an example here, [the docs for `Vec::push`](https://doc.rust-lang.org/src/alloc/vec/mod.rs.html#1489). This can be rendered by IDEs or into websites like you can see [here](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.push).

2021-04-29 01:39 UTC, George-lewis commented on src/main.rs
> +    } else if input.contains("=") {
Can this be a char like line 103?

2021-04-29 02:00 UTC, George-lewis requested changes

2021-04-29 02:00 UTC, George-lewis commented on src/lib/errors.rs
> +    Assignment,
I hate to say it, but this feels like muddling CLI and backend concerns, given that assignment is something implemented purely in the interface code. Unfortunately we might have to nest errors here, something like:

```rust
enum CliError {
  Assignment,
  Library(Error)
}
```

which can be matched like:

```rust
match error {
  CliError::Assignment => ...,
  CliError::Library(inner) => {
    match inner {
      Error::EmptyStack => ...,
      ...
    }
  }
}
```

You can alleviate some of the pain this causes by [`impl From<Error> for CliError`](https://doc.rust-lang.org/std/convert/trait.From.html)

---

I wonder if there could be a better way, there's a lot of crates out there for graceful error handling, I'll have to look into it

2021-04-29 03:47 UTC, kinseyda commented on src/main.rs
> +    } else if input.contains("=") {
Fixed with 24b79e5237619c3eed5608e18b574f2ee324ec76

2021-04-29 04:26 UTC, kinseyda commented on src/lib/errors.rs
> +    Assignment,
Resolved as stated, a new enum has been created to encompass errors in the library for code in the Cli, see f01deaaa794ccb84e35c1e8591a0e1e458a25552

2021-04-29 04:27 UTC, George-lewis requested changes

2021-04-29 04:27 UTC, George-lewis commented on src/main.rs
> +                println!(
It looks like this code that draws a red squiggle underneath the text is going to get reused a bit. Consider refactoring into a function.

2021-04-29 17:44 UTC, kinseyda commented on src/main.rs
> +                println!(
Fixed with 84c1762f24eb71a382465f427e23c0dd8e799487

2021-04-29 18:30 UTC, George-lewis commented on src/main.rs
> +    let conf_string = assign_var_conf_string(repr, &user_repr, user_value);
Inline this function

2021-04-29 20:16 UTC, kinseyda commented on src/main.rs
> +    let conf_string = assign_var_conf_string(repr, &user_repr, user_value);
I'm assuming you mean just put this line in the Ok() at the end? Correct me if I'm wrong, but I don't believe this is doable, since I need to drop the `repr` vector before I can mutate `vars` (the `assign_var()` call right after this line) because the lifetime of `repr` is the immutable borrow of  `vars` by `doeval()`

2021-04-29 21:06 UTC, George-lewis commented on src/lib/variables.rs
> +    /// Searches for the first variable in `vars` that matches the representation given by `text`
+ text must start with the name of a variable (matching case) but can be arbitrarily long

2021-04-29 21:12 UTC, George-lewis commented on src/main.rs
> +    let conf_string = assign_var_conf_string(repr, &user_repr, user_value);
I mean delete the function and insert the code here.

2021-04-29 22:21 UTC, kinseyda commented on src/lib/variables.rs
> +    /// Searches for the first variable in `vars` that matches the representation given by `text`
The documentation has been clarified with 5cb996f97f0584b65421db8089e7adb622a60222

2021-04-29 22:22 UTC, kinseyda commented on src/main.rs
> +    let conf_string = assign_var_conf_string(repr, &user_repr, user_value);
Resolved with 674a8b7bd1af807a05c0fa85a8e71182d6f6b1be

2021-04-29 22:40 UTC, George-lewis approved these changes

2021-04-29 22:54 UTC, George-lewis commented
I found an issue. For some reason when the input string ends with a `$`, `make_highlighted_error` panics on line 191.

![image](https://user-images.githubusercontent.com/33588728/116628036-4d89ff80-a91c-11eb-957f-3a1a56089efb.png)

2021-04-30 01:22 UTC, George-lewis commented on src/main.rs
>          #[allow(clippy::single_match_else)]
We can probably remove this now

2021-04-30 01:23 UTC, George-lewis commented on src/main.rs
> +        assign_var(vars, x, "ans".to_string()); // Set ans to new value
`assign_var` should take a `&str` and create a `String` only if necessary

2021-04-30 02:36 UTC, merged

2021-04-30 02:36 UTC, George-lewis commented
Thank you for your help